Syllad core library 1.0 loaded.
syllad self-hosting compiler
tokenizing "syd.syd"...
parsing...
tokenizing "syd-tokenizer.syd"...
parsing...
tokenizing "core.syd"...
parsing...
tokenizing "syd-ast.syd"...
parsing...
